# Generated by Django 4.2.7 on 2023-11-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_customer_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_service',
            name='answer',
            field=models.CharField(max_length=500),
        ),
    ]
