# Generated by Django 4.2.7 on 2023-12-07 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminPanel", "0003_alter_customer_service_answer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="customer_service",
        ),
    ]
