# Generated by Django 4.2.6 on 2023-10-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='joining_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
