# Generated by Django 4.2.6 on 2023-10-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_book_isbn_book_created_by_book_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.CharField(max_length=500),
        ),
    ]
