# Generated by Django 4.2.6 on 2023-10-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_book_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='download_link',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
