# Generated by Django 4.2.6 on 2023-10-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_wishlist_delete_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='book',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='books',
            field=models.ManyToManyField(to='home.book'),
        ),
    ]
