# Generated by Django 4.2.6 on 2023-10-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_wishlist_book_wishlist_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
