# Generated by Django 4.2.6 on 2023-10-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
