# Generated by Django 4.2.6 on 2023-10-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
