# Generated by Django 4.2.7 on 2023-11-29 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='book',
        ),
    ]
