# Generated by Django 4.2.7 on 2023-11-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_product_cartitem_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=10, max_length=3),
            preserve_default=False,
        ),
    ]
