# Generated by Django 4.2.6 on 2023-10-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='books',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='books',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
