# Generated by Django 4.2.6 on 2023-10-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_comment'),
        ('user', '0003_remove_wishlist_books_wishlist_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='books',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='books',
            field=models.ManyToManyField(to='home.book'),
        ),
    ]
