# Generated by Django 4.2.6 on 2023-10-27 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_comment'),
        ('user', '0004_remove_wishlist_books_wishlist_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='books',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.book'),
            preserve_default=False,
        ),
    ]
